import type { Language } from "@/lib/language";

export const uiText = {
  ja: {
    stats: "ステータス",
    comment: "ひとことコメント",
    compatibility: "相性◎の恋愛ジョブ",
    partyInvite: "このタイプの人、私のパーティに来てください",
    shareNative: "冒険結果をシェア",
    shareResult: "結果をシェア",
    saveImage: "PNGで保存",
    screenshotHint: "保存できない時はスクショしてシェアしてね",
    shareX: "X / Twitterで共有",
    shareThreads: "Threadsで共有",
    copy: "コピー",
    retry: "もう一度冒険する",
    library: "恋愛ジョブ図鑑を見る",
    libraryTitle: "恋愛ジョブ図鑑",
    libraryDescription: "16種類の恋愛RPGジョブを集める図鑑です。気になるカードを開くと、詳しい恋愛傾向と相性の理由が見られます。",
    libraryBanner: "♥ あなたの恋の仲間カードを探そう ✦ 16 JOB COLLECTION ♥",
    currentJob: "あなたのジョブ",
    discovered: "発見済み",
    start: "冒険をはじめる",
    backToLibrary: "図鑑へ戻る",
    backToTitle: "タイトルへ戻る",
    status: "JOB STATUS",
    detailedTraits: "詳しい特徴",
    strengths: "強み",
    weaknesses: "弱み",
    description: "タイプ説明",
    shareQuestion: "あなたはどの恋愛ジョブ？",
    shareHash: "#ラブクエスト診断",
    homeTitle: "ラブクエスト診断",
    homeDescription: "24問の5段階回答で、あなたの恋愛スタイルを16タイプのファンタジー職業に分類します。",
    homeAxisDescription: "情熱か安定か、主導か寄り添いか、ロマンか現実か、表現か内省か。4つの軸からあなたの恋のジョブを鑑定します。",
    quizTitle: "恋の冒険ログ",
    quizDescription: "1は左寄り、5は右寄り。直感で選ぶほど、あなたのジョブが見えやすくなります。",
    questLabel: "LOVE QUEST",
    neutral: "どちらでも",
    selectAnswer: "を選択",
    backQuestion: "前の質問へ戻る",
    resetQuiz: "最初からやり直す",
  },
  en: {
    stats: "Stats",
    comment: "Quick Comment",
    compatibility: "Best Match Jobs",
    partyInvite: "Please join my party if this is you",
    shareNative: "Share Result",
    shareResult: "Share Result",
    saveImage: "Save PNG",
    screenshotHint: "If saving does not work, take a screenshot and share it.",
    shareX: "Share on X / Twitter",
    shareThreads: "Share on Threads",
    copy: "Copy",
    retry: "Start Another Quest",
    library: "View Love Job Library",
    libraryTitle: "Love Job Library",
    libraryDescription: "Collect all 16 romance RPG jobs. Open a card to see modern relationship traits and why the match works.",
    libraryBanner: "♥ Find your romance party member ✦ 16 JOB COLLECTION ♥",
    currentJob: "Your Job",
    discovered: "Found",
    start: "Start Quest",
    backToLibrary: "Back to Library",
    backToTitle: "Back to Title",
    status: "JOB STATUS",
    detailedTraits: "Detailed Traits",
    strengths: "Strengths",
    weaknesses: "Watch-outs",
    description: "Description",
    shareQuestion: "Which romance job are you?",
    shareHash: "#LoveQuestDiagnosis",
    homeTitle: "Love Quest Diagnosis",
    homeDescription: "Answer 24 quick questions to discover your romance style as one of 16 fantasy RPG jobs.",
    homeAxisDescription: "Passion or steadiness, leading or supporting, romance or realism, expressive or reflective. Your four axes reveal your love job.",
    quizTitle: "Romance Quest Log",
    quizDescription: "1 leans left, 5 leans right. Go with your gut to reveal your job more clearly.",
    questLabel: "LOVE QUEST",
    neutral: "Neutral",
    selectAnswer: "Select",
    backQuestion: "Back to Previous Question",
    resetQuiz: "Restart from the Beginning",
  },
  ko: {
    stats: "스테이터스",
    comment: "한줄 코멘트",
    compatibility: "궁합◎ 연애 직업",
    partyInvite: "이 타입이라면 제 파티에 와주세요",
    shareNative: "모험 결과 공유",
    shareResult: "결과 공유",
    saveImage: "PNG 저장",
    screenshotHint: "저장이 안 되면 스크린샷으로 공유해 주세요.",
    shareX: "X / Twitter에 공유",
    shareThreads: "Threads에 공유",
    copy: "복사",
    retry: "다시 모험하기",
    library: "연애 직업 도감 보기",
    libraryTitle: "연애 직업 도감",
    libraryDescription: "16가지 연애 RPG 직업을 모으는 도감입니다. 카드를 열면 현실적인 연애 성향과 궁합 이유를 볼 수 있어요.",
    libraryBanner: "♥ 나의 연애 파티원을 찾아보자 ✦ 16 JOB COLLECTION ♥",
    currentJob: "나의 직업",
    discovered: "발견 완료",
    start: "모험 시작",
    backToLibrary: "도감으로",
    backToTitle: "타이틀로",
    status: "JOB STATUS",
    detailedTraits: "자세한 특징",
    strengths: "강점",
    weaknesses: "주의점",
    description: "타입 설명",
    shareQuestion: "당신은 어떤 연애 직업?",
    shareHash: "#러브퀘스트진단",
    homeTitle: "러브 퀘스트 진단",
    homeDescription: "24개의 5점 질문으로 나의 연애 스타일을 16가지 판타지 RPG 직업으로 알아봅니다.",
    homeAxisDescription: "열정과 안정, 주도와 배려, 로맨스와 현실감, 표현과 내면. 네 가지 축으로 나의 연애 직업을 감정합니다.",
    quizTitle: "연애 모험 로그",
    quizDescription: "1은 왼쪽, 5는 오른쪽에 가까워요. 직감대로 고를수록 직업이 더 선명해집니다.",
    questLabel: "LOVE QUEST",
    neutral: "중간",
    selectAnswer: "선택",
    backQuestion: "이전 질문으로",
    resetQuiz: "처음부터 다시",
  },
} satisfies Record<Language, Record<string, string>>;
